### ISSUE TITLE
Incompatibility with Enhanced Block Entities

### ISSUE THREAD

**Issue by notabirb1** [Nettakrim/Signed-Paintings#1]
With [Enhanced Block Entities](https://modrinth.com/mod/ebe) installed and the option "Enhanced Signs" enabled, images don't render, and the signs show as normal. This is probably caused by the "Enhanced Signs" option using a completely different renderer than vanilla for signs, which overrides any changes by Signed Paintings.

Currently, this bug / incompatibility can be worked around by disabling "Enhanced Signs" in the EBE config menu:
![image](https://github.com/Nettakrim/Signed-Paintings/assets/77424040/1ed41a56-3950-4ee4-9e82-94c47eb87f96)

Due to the easy workaround and fairly obvious cause, this isn't really a major issue, but it may be confusing for some who don't know about it.

*(P.S. This is a really cool mod, great work!)*

**Comment by Nettakrim** [comment]
huh looking at https://github.com/search?q=repo%3AFoundationGames/EnhancedBlockEntities%20renderEnhancedSigns&type=code i dont actually see where the conflict is, i think they indirectly override the rendering so its not obvious where it gets messed with - ill investigate next week

**Comment by Nettakrim** [comment]
fixed in next version (1.0.2)
