### ISSUE TITLE
Self hostable image sharing service

### ISSUE THREAD

**Issue by robotter112** [Nettakrim/Signed-Paintings#14]
I encountered the problem that Imgur blocked the IP address of some players and the images would not load for them. That's why I came up with the idea of running an image sharing service myself, such as Picsur https://github.com/CaramelFur/Picsur, to give people maximum fun and freedom. Do you think that would be feasible as Picsur also has an API interface.

**Comment by robotter112** [comment]
Another cool alternative would be https://github.com/chibisafe/chibisafe

**Comment by BondarenkoArtur** [comment]
@robotter112 You already can do that. 
Just add your domain into config file that is located at `config/signed_paintings.txt` 
But you will need to add it for every client, otherwise image will not be shown.

It's better not to add self-hosted solutions to default list, as it might be security concern.

**Comment by BondarenkoArtur** [comment]
Here is example.
I've added `https://avatars.githubusercontent.com/` to the list

And here is your avatar showing without uploading to imgur
![Screenshot_20240619_173612](https://github.com/Nettakrim/Signed-Paintings/assets/9720950/33029596-3e7f-4a16-ba51-6d1adee496a0)
![Screenshot_20240619_173534](https://github.com/Nettakrim/Signed-Paintings/assets/9720950/f3d85750-c8f1-468f-b82a-733a20b1512c)

**Comment by Nettakrim** [comment]
i also probably wont be adding an ingame command to modify the allowed url domains, since the format isnt really intuitive

**Comment by BondarenkoArtur** [comment]
I guess we can close it then
