### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by pocinhas** [Nettakrim/Signed-Paintings#2]
crashing whenever i touch the offset slider/number box
[crash-2023-08-21_17.53.01-client.txt](https://github.com/Nettakrim/Signed-Paintings/files/12398806/crash-2023-08-21_17.53.01-client.txt)

**Comment by Nettakrim** [comment]
i cant do much for a week, but it *might* be an incompatibility with the mod "fabrication & forgery"

**Comment by pocinhas** [comment]
k, i'll check and report the results

**Comment by pocinhas** [comment]
seemed like you were right, although whem i deactived some options on fabrication's config that showed up when i searched "sign" and it stopped occurring. no idea if its just a coincidence or if theres a specific fabrication option that breaks signed paintings. if i figure something else out, ill let you know

**Comment by pocinhas** [comment]
update: it was just a coincidence, the game crashed shortly after anyways (when messing with the signed paintings GUI)

**Comment by Nettakrim** [comment]
looking at the crash report i think it happens based the length of the text that was on the sign and the length that will be on the sign - if you send me a list of what mods you're using i can investigate properly next week

**Comment by pocinhas** [comment]
hey man, sorry i completely forgot to get back to you on this but it seems that this is no longer an issue, at least it hasnt been for a while :D

edit: nevermind 💀 
[modlist.txt](https://github.com/Nettakrim/Signed-Paintings/files/12614271/modlist.txt)
(sorry i had no idea how to export the modlist through prismlauncher so i just copied it from the log)

**Comment by Nettakrim** [comment]
fixed in next update
