### ISSUE TITLE
The gui doesnt show up when pasting an image

### ISSUE THREAD

**Issue by CalciB** [Nettakrim/Signed-Paintings#21]
Tried with a few different links, only the upload to imgur button shows up when external link is given. 
![image](https://github.com/Nettakrim/Signed-Paintings/assets/108853112/889a9acd-6384-4b1a-9847-9b449f426215)

**Comment by Nettakrim** [comment]
what version are you using? some older ones may be broken (there are also known issues with uploading in the recent versions)

**Comment by CalciB** [comment]
Ah i was using 1.0.3 which was on curseforge seems it has updated to 1.0.5 on modrinth, Thank you!

**Comment by Nettakrim** [comment]
oh lol did i forget cf ahaha, i should definately fix that
