### ISSUE TITLE
Aftep pasting Url image doesn't appear

### ISSUE THREAD

**Issue by BondarenkoArtur** [Nettakrim/Signed-Paintings#29]
![image](https://github.com/Nettakrim/Signed-Paintings/assets/9720950/73126765-d92c-4e87-b977-0c2e68cf419e)
https://i.imgur.com/qtwhgAE.jpeg
I assume issue because of .jpeg

**Comment by Nettakrim** [comment]
yeah i noticed that with another image, if it fails to dowload and image and convert it into a texture it doesnt display
if you turn on detailed logs in config it might tell you more about why

**Comment by BondarenkoArtur** [comment]
My friend sent me that. 
Will take a look into details and try to reproduce soon

**Comment by BondarenkoArtur** [comment]
Cannot reproduce, closing
