### ISSUE TITLE
Sign doesn't disappear when uploaded

### ISSUE THREAD

**Issue by lostdoge08** [Nettakrim/Signed-Paintings#34]
Says in the title, when I place an image, the sign is still visible, blocking the image.
I'm on Minecraft version 1.20.1. Could very much be a mod incompatibility issue in which I will try to see which mod it is.
![image](https://github.com/Nettakrim/Signed-Paintings/assets/146174915/57958376-2ea9-45da-9012-00d07a1f8b57)

**Comment by Nettakrim** [comment]
looks like enhanced block entities, you can go into modmenu, look for it, then disable enhaced signs to make the sign get hidden

**Comment by lostdoge08** [comment]
ooooo thank you!!!
