### ISSUE TITLE
[feature request] url whitelist

### ISSUE THREAD

**Issue by EnderMelody** [Nettakrim/Signed-Paintings#4]
not sure if this is already a thing, but would it be possible to implement a url whitelist as i am worried about potential security issues with the mod trying to load any url it is given.

**Comment by Nettakrim** [comment]
you can *sort of* do this by doing /paintings:block auto (dont remember the exact command) then /paintings:block remove \<urls>, but that isnt a good solution

the mod even goes out of its way to make whatever on the sign become a url :P definitely should have something

**Comment by Nettakrim** [comment]
okay ive just made it so that only certain domains (specifically `https://i.imgur.com/` `https://iili.io/` `https://i.ibb.co/`) will be allowed - this is also semi configurable (in that you can edit a file to allow more)

**Comment by Windoooors** [comment]
Could you tell me where and how I can edit that file?
Connections to these default sites are extremely slow in China though
Urgent needs of allowing more sites!

**Comment by Nettakrim** [comment]
the file might only appear once you do `/paintings:block <anything>` then relog, the file is .minecraft/signed_paintings.txt which looks something like this
```
- Blocked Painting URLs -
- Allowed URL Domains -
https://i.imgur.com/
https://iili.io/
https://i.ibb.co/
```

the allowed domains just work by whether the specified domain stars with the allowed thing, meaning replacing the file with
```
- Blocked Painting URLs -
- Allowed URL Domains -
https
```
will allow any url starting with https

**Comment by Windoooors** [comment]
Thanks!
